# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Download\OneDrive - zju.edu.cn\code\temp\AAA\ui\chart.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_chartForm(object):
    def setupUi(self, chartForm):
        chartForm.setObjectName("chartForm")
        chartForm.resize(686, 301)
        self.horizontalLayout = QtWidgets.QHBoxLayout(chartForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(chartForm)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.chart = QChart(chartForm)
        self.chart.setObjectName("chart")
        self.horizontalLayout.addWidget(self.chart)

        self.retranslateUi(chartForm)
        QtCore.QMetaObject.connectSlotsByName(chartForm)

    def retranslateUi(self, chartForm):
        _translate = QtCore.QCoreApplication.translate
        chartForm.setWindowTitle(_translate("chartForm", "Form"))
        self.pushButton.setText(_translate("chartForm", "PushButton"))
from PyQt5.QtChart import QChart
