server:
  port: 8100

# eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false
  instance:
    instance-id: springcloud-provider-dept-8100
spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true