server:
  port: 7003
# Eureka配置
eureka:
  instance:
    hostname: eureka7003.com # Eureka服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向Eureka注册中心注册自己
    fetch-registry: false # 表示是否从Eureka注册中心获取注册信息
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/