server:
  port: 8100

# eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: false
  instance:
    instance-id: springcloud-provider-dept-8100
    non-secure-port: ${server.port}
spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        group:
          enabled: true # 开启sentinel的feign支持
      httpclient:
        connection-timeout: 10
        ok-http:
          read-timeout: 10
    circuitbreaker:
      hystrix:
        enabled: true
feign:
  hystrix:
    enabled: true
hystrix:
  shareSecurityContext: true  # 开启hystrix的feign支持