server:
  port: 8002

# mybatis配置
mybatis:
  type-aliases-package: com.bayyy.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

# spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8002

# info信息
info:
  app.name: bayyy # 项目名称
  company.name: bayyy.com # 公司名称
  build.artifactId: ${project.artifactId}  # 项目构建ID
  build.version: ${project.version}  # 项目版本
  build.time: ${maven.build.timestamp}  # 项目构建时间

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]  # 暴露指定端点
  info:
    env:
      enabled: true